name: Scheduled Job

on:
  schedule:
   - cron: '* * * * *'

permissions:
  contents: read

jobs:
  run-scheduled-task:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Get OAuth Token
      - name: Get OAuth Token
        id: get_token
        run: |
          TOKEN="ajcn9i3nvrn9302sadsd"
          echo "TOKEN=$TOKEN" >> $GITHUB_ENV
        
      - name: Call my API endpoint closed
        run: echo "running scheduler ${{ env.TOKEN }}"
